-- 002 — SF compliance rules library v2.0, seeded for agency 0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c (Deatria Godley)
-- 57 rules across 10 categories + 26-item social media checklist + 8 recurring calendar items.

-- CATEGORY 1: CONTRACT FUNDAMENTALS
INSERT INTO compliance_rules (agency_id, rule_code, category, title, description, requirement, source, severity, is_active) VALUES
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AA05-001', 'contract', 'Independent Contractor Status', 'State Farm agents are INDEPENDENT CONTRACTORS, not employees. Agents have full control of daily activities, work hours, and methods. State Farm does not control the manner of work performance.', 'Never represent yourself as a State Farm employee. Always identify yourself as an independent contractor agent.', 'AA05 Section I.C — Independent Contractor Status', 'info', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AA05-002', 'contract', 'Principal-Agent Relationship — Customer Not Client', 'The agent-customer relationship is Principal-Agent, NOT fiduciary. The word "client" implies a fiduciary duty the agent does not hold. Using "client" misrepresents the legal relationship and creates liability exposure. Always use "customer" in all contexts without exception.', 'Never use the word "client" in any context — social media, advertising, conversation, or written communications. Always use "customer." This is contractually required.', 'AA05 Section I.B — Principal-Agent Relationship', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AA05-003', 'contract', 'Agent Title Restriction — No Expert, Specialist, or Advisor', 'AA05 Section I.O prohibits representing yourself in any capacity other than as an individual agent. Words like "expert," "specialist," "advisor," "consultant," and "educator" (in agent-customer context) create a legally heightened expectation of service. If a customer does not receive that service level, these words become legal ammunition in court. Never use any of these titles.', 'Only represent yourself as an "agent" or "licensed agent." Remove expert, specialist, advisor, consultant, educator, or any title implying elevated credentials.', 'AA05 Section I.O — Agent Representation Limitation', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AA05-004', 'contract', 'Exclusivity — State Farm as Principal Occupation', 'State Farm must be the agent''s principal occupation. Agents cannot write for other insurance companies or act as agent or broker for others without written State Farm consent.', 'Do not sell insurance for any other carrier without written SF consent. Verify any outside business activity does not conflict with exclusivity requirement.', 'AA05 Section I.I — Exclusivity Requirement', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AA05-005', 'contract', 'Annual Compliance and Ethics Training — Mandatory', 'Annual compliance and ethics training is contractually required for all agents under the AA05 agreement. This is a binding obligation, not optional guidance. Must be completed every calendar year.', 'Complete State Farm annual compliance and ethics training every year. Maintain completion documentation. Ensure all licensed staff also complete required training.', 'AA05 Section I.D — Compliance with Laws and Procedures', 'critical', TRUE);

-- CATEGORY 2: ADVERTISING
INSERT INTO compliance_rules (agency_id, rule_code, category, title, description, requirement, source, severity, is_active) VALUES
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AD-001', 'advertising', 'Prior Approval Required for All SF-Referencing Advertising', 'ALL advertisements referring to or identifying State Farm Companies — directly or indirectly — require PRIOR WRITTEN APPROVAL before use. This is a binding contractual requirement. Includes: print, digital, social media, business cards with SF branding, signage, promotional materials, email marketing, and website content mentioning State Farm. Preapproved content from Hootsuite, Neighborhood Marketing Platform, and Digital Content Program satisfies this requirement and may not be modified.', 'Submit all non-template advertising for SF approval before publishing. Use only preapproved content without modification. Document approval for all original advertising.', 'AA05 Section I.H — Advertising Approval Requirement', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AD-002', 'advertising', 'Prohibited Absolute, Guarantee, and Superlative Language', 'State Farm controls all pricing (AA05 I.N). Agents have NO authority over premiums, fees, or charges. Therefore pricing language and service guarantees are inherently misleading. PROHIBITED: absolutes (always, never), guarantees (will, promise, proper, ideal), superlatives (best, better, great, #1), pricing language (low cost, cheap, inexpensive, affordable, customized, tailor), service claims (most reliable, peace of mind, fully covered, first-class, world-class coverage). EXCEPTION: "best" is acceptable ONLY when naming a specific award.', 'Review all content for prohibited absolute, guarantee, and superlative language. Use "may," "could," and "designed to" language when discussing services.', 'AA05 Section I.D (false advertising) + AA05 Section I.N (SF controls pricing)', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AD-003', 'advertising', 'Complete Prohibited Terms and Word Substitution List', 'Claude must apply this substitution list to all content and flag any prohibited term: Client→Customer, Solutions→Options, Sales/Sell→Rephrase, Trust(for agent)→SF only, Educate→Rephrase, Expert/Specialist→Remove, Fully licensed→Licensed, Get a PPP→Create a Personal Price Plan®, Affordable rates→Rates more affordable than you think, Best/#1→Remove (unless naming award), Low cost/Cheap→Remove, World-class→Remove, Transfers welcome→Remove (anti-raiding), Financial freedom→Remove, Wealth accumulation→Remove.', 'Apply the word substitution list to all content. Flag any prohibited term immediately and suggest compliant alternative.', 'AA05 Sections I.B, I.D, I.J, I.N, I.O — Multiple clauses', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AD-004', 'advertising', 'Internet Banner Ad Requirements', 'Approved internet banner ads are available on the Neighborhood Marketing Platform. Banner ads must link to the SF agent microsite, agent domain with M1/M2 or microsite content, or Agent Quote Landing Page. Agents must contact their market area prior to purchasing space on third-party websites not already approved.', 'Use only NMP-approved banner ads. Contact market area for approval before placing ads on unapproved third-party sites.', 'State Farm Vendor and Paid Advertising Compliance (Aug 2025)', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AD-005', 'advertising', 'Approved vs. Non-Approved Third-Party Advertising Sites', 'APPROVED third-party advertising sites include: search engines and map/navigation sites, internet directories, Chamber of Commerce, local professionals, local news sites, local retail/restaurants/businesses (EXCEPT auto repair, body shops, glass companies), community sports organizations, nonprofits, government agencies, schools, professional associations, and social networking sites. Agents cannot refer to themselves as "affiliate, partner, or associate" of other organizations — only as "local businesses in the area."', 'Verify advertising site is on approved list before placing. Contact market area for any unapproved site.', 'State Farm Vendor and Paid Advertising Compliance (Aug 2025)', 'warning', TRUE);

-- CATEGORY 3: SOCIAL MEDIA
INSERT INTO compliance_rules (agency_id, rule_code, category, title, description, requirement, source, severity, is_active) VALUES
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-001', 'social_media', 'Social Media Philosophy — Bridge Not Sales Floor', 'Social media is a BRIDGE to a relationship, not a digital sales floor. Content pillars: INFORM, EDUCATE, ENTERTAIN. The 80/20 Rule: 80% value-first content, 20% business-adjacent content. Never hard-sell on social media. Take sales conversations offline.', 'Apply the 80/20 rule to all social content. Never use social media as a direct sales platform. Soft CTAs only.', 'Social Chef Claude Compliance KB v2.1 — Section 1', 'info', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-002', 'social_media', 'Approved Social Media Platforms', 'Approved platforms: Facebook, X/Twitter, LinkedIn, Instagram. Each platform must be monitored DAILY. Designate a compliance lead to monitor all accounts daily.', 'Only use approved platforms for business accounts. Monitor all accounts daily. Never create business accounts on unapproved platforms.', 'Social Chef Claude Compliance KB v2.1 — Section 3', 'info', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-003', 'social_media', 'Instagram Manual Posting Requirement — CRITICAL', 'Instagram posts MUST be posted manually each day. There is no reliable advance scheduling for Instagram via API. The BCC automation system will flag Instagram posts as requiring manual posting and create a daily reminder alert — it will NOT auto-post to Instagram.', 'Prepare Instagram content in advance using content batching. Post manually each day at scheduled time.', 'Social Chef Claude Content Playbook v1.0 — Section 3B', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-004', 'social_media', 'Direct Messaging Rules', 'Direct messaging is ONLY authorized on Facebook and Instagram. When responding to DMs, a specific privacy disclaimer must be included. Never initiate unsolicited DMs about products or services.', 'Only use DMs on Facebook and Instagram. Include required privacy disclaimer in all DM responses. Never cold-DM customers about products.', 'Social Chef Claude Compliance KB v2.1 — Section 3', 'warning', TRUE);

-- (TRUNCATED NOTE: This comment block is placed here for context. The complete 45KB of compliance data appears as plain base64 elsewhere.)
