-- 002 — SF compliance rules library v2.0, seeded for agency 0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c (Deatria Godley)
-- 57 rules across 10 categories + 26-item social media checklist + 8 recurring calendar items.

-- CATEGORY 1: CONTRACT FUNDAMENTALS
INSERT INTO compliance_rules (agency_id, rule_code, category, title, description, requirement, source, severity, is_active) VALUES
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AA05-001', 'contract', 'Independent Contractor Status', 'State Farm agents are INDEPENDENT CONTRACTORS, not employees. Agents have full control of daily activities, work hours, and methods. State Farm does not control the manner of work performance.', 'Never represent yourself as a State Farm employee. Always identify yourself as an independent contractor agent.', 'AA05 Section I.C — Independent Contractor Status', 'info', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AA05-002', 'contract', 'Principal-Agent Relationship — Customer Not Client', 'The agent-customer relationship is Principal-Agent, NOT fiduciary. The word "client" implies a fiduciary duty the agent does not hold. Using "client" misrepresents the legal relationship and creates liability exposure. Always use "customer" in all contexts without exception.', 'Never use the word "client" in any context — social media, advertising, conversation, or written communications. Always use "customer." This is contractually required.', 'AA05 Section I.B — Principal-Agent Relationship', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AA05-003', 'contract', 'Agent Title Restriction — No Expert, Specialist, or Advisor', 'AA05 Section I.O prohibits representing yourself in any capacity other than as an individual agent. Words like "expert," "specialist," "advisor," "consultant," and "educator" (in agent-customer context) create a legally heightened expectation of service. If a customer does not receive that service level, these words become legal ammunition in court. Never use any of these titles.', 'Only represent yourself as an "agent" or "licensed agent." Remove expert, specialist, advisor, consultant, educator, or any title implying elevated credentials.', 'AA05 Section I.O — Agent Representation Limitation', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AA05-004', 'contract', 'Exclusivity — State Farm as Principal Occupation', 'State Farm must be the agent''s principal occupation. Agents cannot write for other insurance companies or act as agent or broker for others without written State Farm consent.', 'Do not sell insurance for any other carrier without written SF consent. Verify any outside business activity does not conflict with exclusivity requirement.', 'AA05 Section I.I — Exclusivity Requirement', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AA05-005', 'contract', 'Annual Compliance and Ethics Training — Mandatory', 'Annual compliance and ethics training is contractually required for all agents under the AA05 agreement. This is a binding obligation, not optional guidance. Must be completed every calendar year.', 'Complete State Farm annual compliance and ethics training every year. Maintain completion documentation. Ensure all licensed staff also complete required training.', 'AA05 Section I.D — Compliance with Laws and Procedures', 'critical', TRUE);

-- CATEGORY 2: ADVERTISING
INSERT INTO compliance_rules (agency_id, rule_code, category, title, description, requirement, source, severity, is_active) VALUES
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AD-001', 'advertising', 'Prior Approval Required for All SF-Referencing Advertising', 'ALL advertisements referring to or identifying State Farm Companies — directly or indirectly — require PRIOR WRITTEN APPROVAL before use. This is a binding contractual requirement. Includes: print, digital, social media, business cards with SF branding, signage, promotional materials, email marketing, and website content mentioning State Farm. Preapproved content from Hootsuite, Neighborhood Marketing Platform, and Digital Content Program satisfies this requirement and may not be modified.', 'Submit all non-template advertising for SF approval before publishing. Use only preapproved content without modification. Document approval for all original advertising.', 'AA05 Section I.H — Advertising Approval Requirement', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AD-002', 'advertising', 'Prohibited Absolute, Guarantee, and Superlative Language', 'State Farm controls all pricing (AA05 I.N). Agents have NO authority over premiums, fees, or charges. Therefore pricing language and service guarantees are inherently misleading. PROHIBITED: absolutes (always, never), guarantees (will, promise, proper, ideal), superlatives (best, better, great, #1), pricing language (low cost, cheap, inexpensive, affordable, customized, tailor), service claims (most reliable, peace of mind, fully covered, first-class, world-class coverage). EXCEPTION: "best" is acceptable ONLY when naming a specific award.', 'Review all content for prohibited absolute, guarantee, and superlative language. Use "may," "could," and "designed to" language when discussing services.', 'AA05 Section I.D (false advertising) + AA05 Section I.N (SF controls pricing)', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AD-003', 'advertising', 'Complete Prohibited Terms and Word Substitution List', 'Claude must apply this substitution list to all content and flag any prohibited term: Client→Customer, Solutions→Options, Sales/Sell→Rephrase, Trust(for agent)→SF only, Educate→Rephrase, Expert/Specialist→Remove, Fully licensed→Licensed, Get a PPP→Create a Personal Price Plan®, Affordable rates→Rates more affordable than you think, Best/#1→Remove (unless naming award), Low cost/Cheap→Remove, World-class→Remove, Transfers welcome→Remove (anti-raiding), Financial freedom→Remove, Wealth accumulation→Remove.', 'Apply the word substitution list to all content. Flag any prohibited term immediately and suggest compliant alternative.', 'AA05 Sections I.B, I.D, I.J, I.N, I.O — Multiple clauses', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AD-004', 'advertising', 'Internet Banner Ad Requirements', 'Approved internet banner ads are available on the Neighborhood Marketing Platform. Banner ads must link to the SF agent microsite, agent domain with M1/M2 or microsite content, or Agent Quote Landing Page. Agents must contact their market area prior to purchasing space on third-party websites not already approved.', 'Use only NMP-approved banner ads. Contact market area for approval before placing ads on unapproved third-party sites.', 'State Farm Vendor and Paid Advertising Compliance (Aug 2025)', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'AD-005', 'advertising', 'Approved vs. Non-Approved Third-Party Advertising Sites', 'APPROVED third-party advertising sites include: search engines and map/navigation sites, internet directories, Chamber of Commerce, local professionals, local news sites, local retail/restaurants/businesses (EXCEPT auto repair, body shops, glass companies), community sports organizations, nonprofits, government agencies, schools, professional associations, and social networking sites. Agents cannot refer to themselves as "affiliate, partner, or associate" of other organizations — only as "local businesses in the area."', 'Verify advertising site is on approved list before placing. Contact market area for any unapproved site.', 'State Farm Vendor and Paid Advertising Compliance (Aug 2025)', 'warning', TRUE);

-- CATEGORY 3: SOCIAL MEDIA
INSERT INTO compliance_rules (agency_id, rule_code, category, title, description, requirement, source, severity, is_active) VALUES
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-001', 'social_media', 'Social Media Philosophy — Bridge Not Sales Floor', 'Social media is a BRIDGE to a relationship, not a digital sales floor. Content pillars: INFORM, EDUCATE, ENTERTAIN. The 80/20 Rule: 80% value-first content, 20% business-adjacent content. Never hard-sell on social media. Take sales conversations offline.', 'Apply the 80/20 rule to all social content. Never use social media as a direct sales platform. Soft CTAs only.', 'Social Chef Claude Compliance KB v2.1 — Section 1', 'info', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-002', 'social_media', 'Approved Social Media Platforms', 'Approved platforms: Facebook, X/Twitter, LinkedIn, Instagram. Each platform must be monitored DAILY. Designate a compliance lead to monitor all accounts daily.', 'Only use approved platforms for business accounts. Monitor all accounts daily. Never create business accounts on unapproved platforms.', 'Social Chef Claude Compliance KB v2.1 — Section 3', 'info', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-003', 'social_media', 'Instagram Manual Posting Requirement — CRITICAL', 'Instagram posts MUST be posted manually each day. There is no reliable advance scheduling for Instagram via API. The BCC automation system will flag Instagram posts as requiring manual posting and create a daily reminder alert — it will NOT auto-post to Instagram.', 'Prepare Instagram content in advance using content batching. Post manually each day at scheduled time.', 'Social Chef Claude Content Playbook v1.0 — Section 3B', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-004', 'social_media', 'Direct Messaging Rules', 'Direct messaging is ONLY authorized on Facebook and Instagram. When responding to DMs, a specific privacy disclaimer must be included. Never initiate unsolicited DMs about products or services.', 'Only use DMs on Facebook and Instagram. Include required privacy disclaimer in all DM responses. Never cold-DM customers about products.', 'Social Chef Claude Compliance KB v2.1 — Section 3', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-005', 'social_media', 'English-Only Content Requirement', 'ALL business account content must be written in English unless it is preapproved content. FINRA requires ALL communications to be archived and monitored. Proofpoint compliance monitoring software is English-only.', 'Write all original social content in English only. This is a contractual compliance requirement under FINRA archiving rules, not just a preference.', 'AA05 Section I.D + FINRA Rule 2210 + Social Chef Claude Compliance KB v2.1 — Section 12', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-006', 'social_media', 'Staff Social Media Accountability — Agent Liable for All Staff Posts', 'AA05 Section I.P makes the agent "responsible for your staffs'' activities." Agents are contractually liable for EVERY social media post their staff creates, shares, or publishes on behalf of the agency. The agent — not the staff member — bears contractual responsibility for violations.', 'Train all staff on compliance rules before granting social media account access. Review staff content before publishing. Document training completion.', 'AA05 Section I.P — Agent Responsible for Staff Activities', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-007', 'social_media', 'AI-Generated Content Disclaimer Required', 'Any AI-produced or AI-enhanced images or videos REQUIRE disclaimers per platform Terms and Conditions. Examples of compliant disclaimers: "Created with the help of AI" or "AI-generated." This is required by platform rules, not optional.', 'Include AI disclaimer on all AI-generated or AI-enhanced visual content before posting to any platform.', 'Platform Terms and Conditions — All Major Platforms', 'warning', TRUE);

-- CATEGORY 4: ABSOLUTE SOCIAL MEDIA PROHIBITIONS
INSERT INTO compliance_rules (agency_id, rule_code, category, title, description, requirement, source, severity, is_active) VALUES
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-PROHIBIT-001', 'social_media', 'Absolutely Prohibited Social Media Topics', 'These topics may NEVER appear on any agent social media account: Investment Planning Services and Mutual Funds, State Farm College Savings Plans (529 plans), specific life or health insurance products BY NAME, pricing models/specific rates/premium amounts, internal State Farm processes, incentive programs (ScoreCard details, bonus structures), proprietary State Farm information, claims and underwriting rules, rates and rating processes, internal programs/tools/contracts, budgets and allocations.', 'Immediately flag and refuse any request to create content touching these prohibited topics. Explain why and suggest compliant alternatives.', 'AA05 Section I.D, I.F, I.H, I.N + Social Chef Claude Compliance KB v2.1 — Section 4', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-PROHIBIT-002', 'social_media', 'Customer Data — Absolute Prohibition', 'Customer information constitutes State Farm''s TRADE SECRETS under AA05 Section I.F. Sharing customer data on social media is misuse of Company trade secrets — a contract violation. Never confirm or deny that someone is a customer in a public review response.', 'Never post, reference, or confirm any customer information on social media. Move all customer discussions to private channels.', 'AA05 Section I.F — Customer Data as Company Trade Secrets + HIPAA BAA', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-PROHIBIT-003', 'social_media', 'No PHI Visible in Photos or Videos', 'Photos and videos must NEVER contain visible Protected Health Information (PHI). The agent''s signed HIPAA Business Associate Agreement (AMD99) creates responsibility for safeguarding all PHI.', 'Review all photos and video backgrounds for any visible PHI before publishing. When in doubt, do not post.', 'HIPAA Business Associate Amendment (AMD99)', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-PROHIBIT-004', 'social_media', 'Trademark and Copyright Prohibitions', 'Agents may not use copyrighted or trademarked terminology or images without permission. Never mention or reference major sporting events, teams, athletes or mascots, or major brand names on business accounts. For giveaways, always use generic descriptions.', 'Avoid all trademark and brand name references in posts. Use generic descriptions for all third-party products and events.', 'Intellectual Property Law + State Farm Business Accounts Guidelines (Sep 2025)', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-PROHIBIT-005', 'social_media', 'No Scare Tactics or Fear-Based Content', 'Agents are prohibited from using scare tactics, fear mongering, or burden language in any content or advertising. Content pillars must be INFORM, EDUCATE, ENTERTAIN — never intimidate.', 'Replace any fear-based language with educational, empowering alternatives. Education not intimidation.', 'AA05 Section I.D — Unfair Practices', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'SM-PROHIBIT-006', 'social_media', 'Written Release Required for All Identifiable People in Photos/Videos', 'A person''s face is their LEGAL PROPERTY under Right of Publicity laws. Written permission is required from every recognizable person in photos or videos.', 'Obtain written releases from ALL identifiable people before posting any photo or video. Maintain release documentation on file.', 'Right of Publicity Laws + Social Chef Claude Compliance KB v2.1 — Section 7', 'critical', TRUE);

-- CATEGORY 5: TRADEMARK
INSERT INTO compliance_rules (agency_id, rule_code, category, title, description, requirement, source, severity, is_active) VALUES
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'TM-001', 'trademark', 'State Farm Name in Social Media Account Names', '"State Farm" in account names is authorized ONLY if immediately followed by "agent." CORRECT: "Jane Doe – State Farm Agent." INCORRECT: "Jane Doe State Farm" or "State Farm Jane."', 'Verify all social media account names follow the "Name – State Farm Agent" format exactly.', 'State Farm Brand Standards + Building Our Brand Guidelines', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'TM-002', 'trademark', 'State Farm Slogan Cannot Be Altered', '"Like a good neighbor, State Farm is there.®" — This slogan must NOT be altered, abbreviated, or paraphrased in any way.', 'Use the State Farm slogan only in its complete, exact form with the registered trademark symbol.', 'State Farm Brand Standards', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'TM-003', 'trademark', 'Personal Price Plan® Correct Usage', 'Must use the full three-word capitalized phrase "Personal Price Plan®" with the registered trademark symbol. Consumers "CREATE" a Personal Price Plan — never "get" one.', 'Write "Personal Price Plan®" in full with trademark symbol always. Consumers always "create" their PPP.', 'State Farm Brand Standards', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'TM-004', 'trademark', 'Google Business Profile — Financial Services Strictly Forbidden', 'Google Business Profile is approved for insurance products ONLY — NOT financial services. STRICTLY FORBIDDEN: financial services, banking products, Certificates of Deposit, annuities, mutual funds, securities, specific life or health insurance products. GBP must be created using the agent''s State Farm Outlook email address.', 'Review all GBP content for insurance-only compliance. Use SF Outlook email for GBP.', 'State Farm Business Accounts Guidelines (Sep 2025)', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'TM-005', 'trademark', 'Multi-Office GBP — Distinct Listing Required per Location', 'Each office location MUST have its own distinct Google Business Profile listing. Never combine or share GBP listings. Never use one phone number across multiple location pages.', 'Verify each office location has a distinct GBP listing with a unique phone number and address.', 'State Farm Business Accounts Guidelines (Sep 2025)', 'warning', TRUE);

-- CATEGORY 6: GIVEAWAYS
INSERT INTO compliance_rules (agency_id, rule_code, category, title, description, requirement, source, severity, is_active) VALUES
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'GIVE-001', 'giveaways', 'No Element of Chance in Any Giveaway — Required', 'Sweepstakes, contests, lotteries, raffles, drawings, and any "enter to win" format are NOT PERMITTED. An element of chance is considered an illegal lottery. EVERY person who takes the specified action MUST receive the item.', 'Structure all giveaways so every participant who takes the specified action receives the item. No lottery, contest, sweepstakes, drawing language ever.', 'State Farm Giveaway Guidelines (Jul 2025)', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'GIVE-002', 'giveaways', 'Giveaway Items — Generic Descriptions Only', 'Giveaway items must be described generically — never using brand or trademark names. COMPLIANT: "coffee shop gift card." NON-COMPLIANT: "Starbucks gift card."', 'Use only generic descriptions for giveaway items. Never mention brand names without written permission.', 'State Farm Giveaway Guidelines (Jul 2025) + Intellectual Property Law', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'GIVE-003', 'giveaways', 'Gift Cards for Quotes — Compliant Structure', 'Agents ARE permitted to offer gift cards in exchange for quotes if properly structured: gift cards cannot be contingent on a sale, include "no purchase necessary" language, stay within state rebating limits.', 'Include "no purchase necessary" in quote-for-gift-card promotions. Give gift card regardless of purchase.', 'State Farm Giveaway Guidelines (Jul 2025)', 'info', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'GIVE-004', 'giveaways', 'Referral Rewards Cannot Be Advertised on Social Media', 'Referral rewards — gift cards, monetary value, actual gifts — may NOT be expressed, advertised, or shared on any social media platform.', 'Keep all referral reward programs in private direct communications only. Never post referral rewards on social media.', 'State Farm Giveaway Guidelines (Jul 2025)', 'critical', TRUE);

-- CATEGORY 7: FINANCIAL
INSERT INTO compliance_rules (agency_id, rule_code, category, title, description, requirement, source, severity, is_active) VALUES
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'FIN-001', 'financial', 'Premium Fund Account — Strict Segregation and Audit Readiness', 'Agents MUST maintain a Premium Fund Account (PFA) at a State Farm-approved bank. This account is held FOR THE BENEFIT OF STATE FARM and is subject to audit at any time. NEVER commingle PFA funds with operating or personal accounts. Maintain 3 months of reconciled PFA bank statements.', 'Maintain separate PFA. Deposit all premiums promptly. Keep PFA box secure with 2 keys only. Never commingle funds.', 'AA05 Section I.K — Premium Trust Account', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'FIN-002', 'financial', 'PFA — Not a Business Asset, Not on Balance Sheet', 'The Policy Financing Arrangement (PFA) is a STATE FARM COMPLIANCE ITEM ONLY. It is NOT a business asset and does NOT appear on the agency balance sheet. Agents may not use PFA as collateral or treat it as an investment asset.', 'Exclude PFA balance from all business financial statements. Never use PFA as collateral. Review with CPA annually.', 'SF PFA Policy Guidelines + Imaginary Farms Standard Accounting Rules', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'FIN-003', 'financial', 'No Rebating or Unauthorized Incentives', 'Agents are absolutely prohibited from offering any rebate, discount, or special favor not specified in the insurance contract as an inducement to purchase insurance. Includes gift cards or free services tied to policy purchases.', 'Never offer anything of value contingent on a policy purchase. Gift cards for quotes are permitted but never for sales.', 'AA05 Section I.D — Unfair Practices + Anti-Rebating Laws', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'FIN-004', 'financial', 'Chargeback Awareness — Commission Recovery Provisions', 'Various SF products include chargeback provisions where commissions may be recovered if policies cancel early. Common chargeback triggers: early cancellations, policy lapses, missing information, non-compliance.', 'Monitor policies for early cancellation risk. Understand chargeback provisions for each product line.', 'AA05 Section II — Compensation and Chargeback Provisions', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'FIN-005', 'financial', 'Agency Financial Health Benchmarks', 'SF Agency Reference Guide benchmarks: Payroll+Taxes/Gross healthy 40-50% warning 51-55% critical >55%. Team Payroll/Gross healthy 30-38% warning 39-45% critical >45%. Owner Comp/Gross healthy 25-35% warning 20-24% critical <20%. Rent/Gross healthy 5-8% warning 9-12% critical >12%. Total OpEx/Gross healthy 15-22% warning 23-28% critical >28%. Net Margin healthy 25-35% warning 20-24% critical <20%.', 'Monitor all financial ratios monthly against these benchmarks. Flag any ratio in warning or critical territory.', 'State Farm Agency Reference Guide v1.0 (Jan 2026)', 'info', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'FIN-006', 'financial', 'Draft Check Sequential Order Required', 'Draft checks must be maintained in sequential order at all times. Compliance audits specifically check for out-of-sequence checks as a red flag for unauthorized or altered transactions.', 'Maintain all draft check sequences in strict sequential order. Verify during monthly compliance review.', 'SF Compliance Review Checklist — Imaginary Farms', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'FIN-007', 'financial', 'Altered Monies History — Monthly Tracking Required', 'History of Altered Monies must be tracked monthly. This is a standing compliance calendar item. Compliance reviews specifically check for altered money activity.', 'Track and review Altered Monies history monthly. Maintain calendar reminder. Document review completion.', 'SF Compliance Review Checklist — Imaginary Farms', 'warning', TRUE);

-- CATEGORY 8: LICENSING
INSERT INTO compliance_rules (agency_id, rule_code, category, title, description, requirement, source, severity, is_active) VALUES
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'LIC-001', 'licensing', 'License Verification Before Any Business Activity', 'CRITICAL: Verify licensing before ANY product sale or binding activity. Required licenses may include P&C, Life, Health, Variable Products (Series 6/63), Bank Products. Staff must be licensed and authorized BEFORE any business activities.', 'Before any sale: verify agent holds required license, confirm license is current, verify involved staff are credentialed. Document verification.', 'AA05 Section I.D + Section I.P — Licensing Requirements', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'LIC-002', 'licensing', 'Continuing Education — Track and Complete by Deadline', 'Must complete state-mandated CE hours in each licensed state during each CE cycle. Failure results in license non-renewal. Maintain CE completion certificates for minimum 4 years.', 'Track CE deadlines and hours for all licensed states and licensed staff. Complete required hours before deadline.', 'State Insurance Department CE Requirements (varies by state)', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'LIC-003', 'licensing', 'E&O Insurance — Never Let It Lapse', 'Agents must maintain current E&O insurance coverage at all times. Lapsed E&O is a contract violation. Flag E&O renewal 90 days before expiration.', 'Track E&O expiration. Begin renewal 90 days before expiration. Never let E&O lapse. Send renewal certificate to SF immediately.', 'SF Agent Agreement — E&O Requirements', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'LIC-004', 'licensing', 'New Team Member — SF Notification and Authorization Required', 'Notify State Farm of all new team member hires within the required timeframe. Complete required background checks before start date. Staff must receive authorization before binding any risk.', 'Notify SF of new hires within required timeframe. Complete background checks before start. Verify all authorizations before licensed activities.', 'AA05 Section I.P + SF Agent Team Member Guidelines', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'LIC-005', 'licensing', 'Monthly Auto Application Compliance Review', 'Required monthly: pull RAZ000BT report, review apps with prior BI/PD coverage less than previous, review SAM report (RAZ000BV), review EUR for HH quoted more than 2 times, review raeap00b agents experience report. Sample 10% of apps per TM.', 'Complete all auto application compliance reviews monthly. Document findings. Address discrepancies with team members immediately.', 'SF Compliance Review Checklist — Imaginary Farms', 'warning', TRUE);

-- CATEGORY 9: DATA PRIVACY
INSERT INTO compliance_rules (agency_id, rule_code, category, title, description, requirement, source, severity, is_active) VALUES
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'PRIV-001', 'data_privacy', 'Customer Data — State Farm Trade Secret Status', 'Customer information constitutes State Farm''s TRADE SECRETS and CONFIDENTIAL BUSINESS INFORMATION wholly owned by the Companies under AA05 Section I.F. At termination, ALL customer data must be returned within 10 days.', 'Treat all customer information as SF trade secrets. Never share customer data outside SF business purposes. Return all customer records within 10 days of any termination.', 'AA05 Section I.F — Customer Data as Trade Secrets', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'PRIV-002', 'data_privacy', 'HIPAA Compliance — PHI Handling and Breach Protocol', 'HIPAA BAA (AMD99) requires: administrative/physical/technical PHI safeguards; report suspected breaches within 48 hours to 1-877-766-6371 AND written notice to Chief Privacy Officer; periodic privacy training; forward access requests to State Farm within 2 business days.', 'Implement PHI safeguards. Report any suspected breach within 48 hours to 1-877-766-6371. Train staff on PHI handling.', 'HIPAA Business Associate Amendment (AMD99)', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'PRIV-003', 'data_privacy', 'Annual Privacy Notice Distribution', 'Agents must send annual GLBA privacy notice to all active customers by November 30 each year. Use SF-approved privacy notice language only.', 'Send annual privacy notice to all active customers by November 30. Document distribution.', 'Gramm-Leach-Bliley Act Privacy Rule', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'PRIV-004', 'data_privacy', 'Written Information Security Program Required', 'Agents must maintain an up-to-date written Information Security Program documenting how the agency protects customer nonpublic personal information.', 'Maintain written Information Security Program. Update annually. Have all employees sign handbook acknowledgment.', 'GLBA Safeguards Rule + SF Compliance Review Checklist', 'warning', TRUE);

-- CATEGORY 10: MEDICARE
INSERT INTO compliance_rules (agency_id, rule_code, category, title, description, requirement, source, severity, is_active) VALUES
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'MED-001', 'medicare', 'Medicare Marketing — CMS Strict Prohibitions', 'CMS regulations: PROHIBITED door-to-door solicitation, telephonic cold calling for Medicare, gifts exceeding $15 CMS limit, marketing in healthcare provider offices (except common areas), claiming to represent Medicare, cross-selling non-health products during Medicare appointments. 48-hour separation between SOA and appointment for additional products.', 'Complete SOA before all individual Medicare appointments. Never cold call for Medicare. Stay within $15 CMS gift limit.', 'CMS Medicare Marketing Guidelines + AA05 Humana Amendment', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'MED-002', 'medicare', 'Scope of Appointment — Documentation Required', 'Scope of Appointment (SOA) documentation is required BEFORE all individual Medicare appointments. A 48-hour separation is required between SOA completion and appointment for additional health products.', 'Complete and obtain signed SOA before every individual Medicare appointment. Maintain SOA documentation on file.', 'CMS SOA Requirements + AA05 Humana Amendment', 'critical', TRUE);

-- CATEGORY 11: 26-ITEM SOCIAL MEDIA CHECKLIST
INSERT INTO compliance_rules (agency_id, rule_code, category, title, description, requirement, source, severity, is_active) VALUES
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-01', 'social_media_checklist', 'Pre-Post Check 1 — No Prohibited Topics', 'Content avoids ALL prohibited topics: investments, mutual funds, college savings plans, specific products by name, pricing, internal SF processes, incentives, claims/underwriting rules.', 'Verify content does not touch any prohibited topic category before publishing.', 'Social Chef Claude Compliance KB v2.1 — Section 18', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-02', 'social_media_checklist', 'Pre-Post Check 2 — Authorized Language Only', 'Content uses only authorized language. Options instead of solutions. Customer instead of client. May/could instead of will/guarantee.', 'Verify all language against the authorized terms list.', 'Social Chef Claude Compliance KB v2.1 — Section 18', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-03', 'social_media_checklist', 'Pre-Post Check 3 — Customer Not Client', '"Customer" is used in all cases. The word "client" is completely absent from the content.', 'Find and replace any instance of "client" with "customer" before publishing.', 'AA05 Section I.B', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-04', 'social_media_checklist', 'Pre-Post Check 4 — Options Not Solutions', '"Options" is used in all cases where "solutions" might appear.', 'Verify "solutions" does not appear anywhere in the content.', 'Social Chef Claude Compliance KB v2.1 — Section 18', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-05', 'social_media_checklist', 'Pre-Post Check 5 — No Absolutes, Guarantees, or Superlatives', 'Content contains no absolute language (always, never), guarantee language (will, promise), or superlatives (best, #1) unless naming a specific award.', 'Scan all content for prohibited absolute, guarantee, and superlative language.', 'AA05 Section I.D + I.N', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-06', 'social_media_checklist', 'Pre-Post Check 6 — No Expert, Specialist, or World-Class', 'Content does not use expert, specialist, world-class, or any elevated professional title beyond "agent" or "licensed agent."', 'Remove any instance of expert, specialist, world-class, or similar elevated titles.', 'AA05 Section I.O', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-07', 'social_media_checklist', 'Pre-Post Check 7 — No Scare Tactics or Fear Mongering', 'Content does not use scare tactics, fear-based language, or burden language.', 'Replace any fear-based language with educational, empowering alternatives.', 'AA05 Section I.D', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-08', 'social_media_checklist', 'Pre-Post Check 8 — No Legal or Financial Advice', 'Content does not constitute legal advice, financial advice, or professional advice-giving beyond general education.', 'Verify content educates without advising.', 'Social Chef Claude Compliance KB v2.1 — Section 18', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-09', 'social_media_checklist', 'Pre-Post Check 9 — All Trademarks Used Correctly', 'State Farm name followed by "agent." SF slogan unaltered if used. Personal Price Plan® written in full with trademark symbol.', 'Verify all trademark usage against brand standards before publishing.', 'Social Chef Claude Compliance KB v2.1 — Section 18', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-10', 'social_media_checklist', 'Pre-Post Check 10 — Personal Price Plan® Correct Usage', 'Personal Price Plan® written in full with trademark symbol. Consumers "create" their PPP — never "get" it.', 'Verify PPP usage meets all brand requirements before publishing.', 'Social Chef Claude Compliance KB v2.1 — Section 18', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-11', 'social_media_checklist', 'Pre-Post Check 11 — AI Disclaimer Included If AI Used in Visuals', 'If AI was used to produce or enhance any images or videos, a required platform disclaimer is included.', 'Include AI disclaimer on all AI-produced or AI-enhanced visual content.', 'Platform T&Cs', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-12', 'social_media_checklist', 'Pre-Post Check 12 — Giveaway: Every Participant Receives Item', 'Any giveaway is structured so every participant who takes the specified action receives the item. No element of chance.', 'Verify giveaway structure guarantees item to every participant who takes action.', 'State Farm Giveaway Guidelines (Jul 2025)', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-13', 'social_media_checklist', 'Pre-Post Check 13 — All Text in English', 'All text is written in English. No tildes, special characters, or in-language text.', 'Verify all original content is written entirely in English.', 'FINRA Rule 2210 + AA05 Section I.D', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-14', 'social_media_checklist', 'Pre-Post Check 14 — No Pricing Specifics or Premium Amounts', 'Content contains no specific pricing, premium amounts, rate quotes, or language implying knowledge of specific rates.', 'Remove any specific pricing, rate, or premium language from content.', 'AA05 Section I.N', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-15', 'social_media_checklist', 'Pre-Post Check 15 — Content Does Not Imply Agent Is the Insurer', 'Content does not imply that the agent — rather than State Farm — is the insurance company or underwriter.', 'Verify content correctly represents agent as distributing SF products.', 'Social Chef Claude Compliance KB v2.1 — Section 18', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-16', 'social_media_checklist', 'Pre-Post Check 16 — Event Photos: No SF Product Info Visible', 'Photos from events do not contain any visible SF product information, policy documents, application forms, or proprietary materials.', 'Review all event photos for visible SF product info before posting.', 'Social Chef Claude Compliance KB v2.1 — Section 18', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-17', 'social_media_checklist', 'Pre-Post Check 17 — No Customer PII or SPI Disclosed', 'Content does not disclose any customer PII or SPI including names, addresses, policy details, or account information.', 'Verify no customer PII or SPI appears anywhere in the content.', 'AA05 Section I.F', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-18', 'social_media_checklist', 'Pre-Post Check 18 — No PHI Visible in Photos or Videos', 'Photos and videos clear of any visible PHI including paperwork, screen displays, or health-related forms.', 'Review all photos and video backgrounds for visible PHI before publishing.', 'HIPAA BAA (AMD99)', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-19', 'social_media_checklist', 'Pre-Post Check 19 — Written Release for All Identifiable People', 'Written permission obtained from every identifiable person in photos or videos.', 'Confirm written releases on file for all identifiable people before posting.', 'Right of Publicity Laws', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-20', 'social_media_checklist', 'Pre-Post Check 20 — State License Numbers Included If Required', 'For AR (life/annuities) or NM (health), the agent state license number is included.', 'Include required state license numbers for AR and NM content.', 'State Insurance Department Requirements', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-21', 'social_media_checklist', 'Pre-Post Check 21 — GBP Posts Are Insurance Products Only', 'Google Business Profile content covers only insurance products. No financial services, banking, annuities, mutual funds, or CDs.', 'Verify all GBP content is insurance-only before posting.', 'State Farm Business Accounts Guidelines (Sep 2025)', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-22', 'social_media_checklist', 'Pre-Post Check 22 — Multi-Office GBP Distinct Listings Verified', 'Each office location has its own distinct GBP listing with unique phone number, address, and details.', 'Verify each office has its own distinct GBP listing before posting.', 'Social Chef Claude Compliance KB v2.1 — Section 18', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-23', 'social_media_checklist', 'Pre-Post Check 23 — DMs Only on Facebook and Instagram with Privacy Disclaimer', 'DMs limited to Facebook and Instagram. Any DM response includes required privacy disclaimer.', 'Verify DM activity is limited to Facebook and Instagram with privacy disclaimer.', 'Social Chef Claude Compliance KB v2.1 — Section 18', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-24', 'social_media_checklist', 'Pre-Post Check 24 — Staff Posts Reviewed by Agent', 'Any content posted by staff members has been reviewed and approved by the agent before publishing.', 'Review and approve all staff social content before it is published. Document approval.', 'AA05 Section I.P', 'critical', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-25', 'social_media_checklist', 'Pre-Post Check 25 — Building Our Brand Guidelines Followed', 'Content follows all SF Building Our Brand guidelines for visual identity, logo usage, color standards, and brand voice.', 'Verify content follows all Building Our Brand guidelines before publishing.', 'State Farm Building Our Brand Guidelines', 'warning', TRUE),
('0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, 'CHECKLIST-26', 'social_media_checklist', 'Pre-Post Check 26 — No Referral Rewards Advertised on Social', 'Content does not advertise referral rewards on any social media platform.', 'Verify content contains no referral reward advertising.', 'State Farm Giveaway Guidelines (Jul 2025)', 'critical', TRUE);

-- COMPLIANCE CALENDAR — recurring annual and monthly items
INSERT INTO compliance_calendar (agency_id, compliance_rule_id, title, description, due_date, recurrence, status, alert_days_before)
SELECT '0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, id,
  'Annual Review: ' || title,
  'Annual compliance review required for: ' || title,
  (DATE_TRUNC('year', NOW()) + INTERVAL '1 year' - INTERVAL '1 day')::DATE,
  'annual', 'upcoming', 30
FROM compliance_rules
WHERE agency_id = '0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID
  AND rule_code IN ('AA05-005','LIC-001','LIC-002','PRIV-004');

INSERT INTO compliance_calendar (agency_id, compliance_rule_id, title, description, due_date, recurrence, status, alert_days_before)
SELECT '0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, id,
  'Annual Social Media Compliance Audit',
  'Complete annual review of all social media profiles. Verify compliance. Apply all 26 checklist items to active posts.',
  (DATE_TRUNC('year', NOW()) + INTERVAL '11 months')::DATE,
  'annual', 'upcoming', 14
FROM compliance_rules WHERE agency_id = '0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID AND rule_code = 'SM-001' LIMIT 1;

INSERT INTO compliance_calendar (agency_id, compliance_rule_id, title, description, due_date, recurrence, status, alert_days_before)
SELECT '0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, id,
  'Annual Customer Privacy Notice Distribution',
  'Send annual GLBA privacy notice to all active customers using SF-approved language.',
  (DATE_TRUNC('year', NOW()) + INTERVAL '11 months')::DATE,
  'annual', 'upcoming', 30
FROM compliance_rules WHERE agency_id = '0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID AND rule_code = 'PRIV-003';

INSERT INTO compliance_calendar (agency_id, compliance_rule_id, title, description, due_date, recurrence, status, alert_days_before)
SELECT '0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, id,
  'W-2 and 1099-NEC Filing Deadline — January 31',
  'Issue all W-2s and 1099-NECs to recipients. File copies with SSA/IRS.',
  (DATE_TRUNC('year', NOW()) + INTERVAL '1 year' + INTERVAL '30 days')::DATE,
  'annual', 'upcoming', 30
FROM compliance_rules WHERE agency_id = '0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID AND rule_code = 'LIC-001' LIMIT 1;

INSERT INTO compliance_calendar (agency_id, compliance_rule_id, title, description, due_date, recurrence, status, alert_days_before)
SELECT '0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, id,
  'E&O Insurance Renewal — Begin Process',
  'Begin E&O insurance renewal process. Confirm coverage amounts meet current SF minimums.',
  (NOW() + INTERVAL '9 months')::DATE,
  'annual', 'upcoming', 90
FROM compliance_rules WHERE agency_id = '0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID AND rule_code = 'LIC-003';

INSERT INTO compliance_calendar (agency_id, compliance_rule_id, title, description, due_date, recurrence, status, alert_days_before)
SELECT '0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, id,
  'Monthly Auto Application Compliance Review',
  'Pull RAZ000BT report. Review all required auto application metrics. Review SAM report (RAZ000BV).',
  (DATE_TRUNC('month', NOW()) + INTERVAL '1 month' - INTERVAL '1 day')::DATE,
  'monthly', 'upcoming', 7
FROM compliance_rules WHERE agency_id = '0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID AND rule_code = 'LIC-005';

INSERT INTO compliance_calendar (agency_id, compliance_rule_id, title, description, due_date, recurrence, status, alert_days_before)
SELECT '0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, id,
  'Monthly Altered Monies History Review',
  'Review and document history of Altered Monies for the month.',
  (DATE_TRUNC('month', NOW()) + INTERVAL '1 month' - INTERVAL '1 day')::DATE,
  'monthly', 'upcoming', 3
FROM compliance_rules WHERE agency_id = '0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID AND rule_code = 'FIN-007';

INSERT INTO compliance_calendar (agency_id, compliance_rule_id, title, description, due_date, recurrence, status, alert_days_before)
SELECT '0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID, id,
  'Monthly PFA Bank Statement Reconciliation',
  'Reconcile Premium Fund Account bank statement. Maintain 3 months of reconciled PFA statements.',
  (DATE_TRUNC('month', NOW()) + INTERVAL '1 month' + INTERVAL '14 days')::DATE,
  'monthly', 'upcoming', 3
FROM compliance_rules WHERE agency_id = '0b8a0268-6b30-4e77-a40a-bc8ee77b5a6c'::UUID AND rule_code = 'FIN-001';;
